manifest = "d07a8f202339d0ff10dee121c080a11b96473ab269ef3b64d401d67e7bfa25a6"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "f07b731f16d83c65fa032285dbc87c1bd181956d"
