manifest = "d07a8f202339d0ff10dee121c080a11b96473ab269ef3b64d401d67e7bfa25a6"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "branch=master" ]
revision = "81e58039a82d50f9c7768c651dce21834557aec1"
